apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-postgresql-storage
  namespace: ci
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: jenkins
